# Generated by Django 5.2.14 on 2026-05-15 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("software_engineer", "Software Engineer"),
                            ("frontend_developer", "Frontend Developer"),
                            ("backend_developer", "Backend Developer"),
                            ("fullstack_developer", "Full Stack Developer"),
                            ("data_scientist", "Data Scientist"),
                            ("data_analyst", "Data Analyst"),
                            ("ui_ux_designer", "UI/UX Designer"),
                            ("graphic_designer", "Graphic Designer"),
                            ("product_manager", "Product Manager"),
                            ("project_manager", "Project Manager"),
                            ("devops_engineer", "DevOps Engineer"),
                            ("qa_engineer", "QA Engineer"),
                            ("business_analyst", "Business Analyst"),
                            ("marketing_specialist", "Marketing Specialist"),
                            ("sales_representative", "Sales Representative"),
                            ("consultant", "Consultant"),
                            ("student", "Student"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=300)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("avatar_color", models.CharField(default="#7c3aed", max_length=7)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
