# Generated by Django 5.2.14 on 2026-05-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="designation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ceo", "Chief Executive Officer (CEO)"),
                    ("cto", "Chief Technology Officer (CTO)"),
                    ("coo", "Chief Operating Officer (COO)"),
                    ("cfo", "Chief Financial Officer (CFO)"),
                    ("engineering_manager", "Engineering Manager"),
                    ("project_manager", "Project Manager"),
                    ("product_manager", "Product Manager"),
                    ("delivery_manager", "Delivery Manager"),
                    ("operations_manager", "Operations Manager"),
                    ("hr_manager", "HR Manager"),
                    ("sales_manager", "Sales Manager"),
                    ("fullstack_developer", "Full Stack Developer"),
                    ("frontend_developer", "Frontend Developer"),
                    ("backend_developer", "Backend Developer"),
                    ("mobile_developer", "Mobile Developer"),
                    ("software_engineer", "Software Engineer"),
                    ("db_handler", "Database Handler / DBA"),
                    ("db_architect", "Database Architect"),
                    ("devops_engineer", "DevOps Engineer"),
                    ("cloud_engineer", "Cloud Engineer"),
                    ("network_engineer", "Network Engineer"),
                    ("security_engineer", "Security Engineer"),
                    ("quality_lead", "Quality Lead"),
                    ("qa_engineer", "QA Engineer / Tester"),
                    ("automation_tester", "Automation Tester"),
                    ("manual_tester", "Manual Tester"),
                    ("performance_tester", "Performance Tester"),
                    ("ui_ux_designer", "UI/UX Designer"),
                    ("product_designer", "Product Designer"),
                    ("graphic_designer", "Graphic Designer"),
                    ("data_scientist", "Data Scientist"),
                    ("data_analyst", "Data Analyst"),
                    ("data_engineer", "Data Engineer"),
                    ("ml_engineer", "ML / AI Engineer"),
                    ("business_analyst", "Business Analyst"),
                    ("scrum_master", "Scrum Master"),
                    ("technical_lead", "Technical Lead"),
                    ("consultant", "Consultant"),
                    ("support_engineer", "Support Engineer"),
                    ("intern", "Intern"),
                    ("student", "Student"),
                    ("other", "Other"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
