# Generated by Django 5.2.14 on 2026-05-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="project",
            name="budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("web_development", "Web Development"),
                    ("mobile_app", "Mobile App"),
                    ("data_science", "Data Science & ML"),
                    ("ui_ux_design", "UI/UX Design"),
                    ("devops", "DevOps & Infrastructure"),
                    ("ecommerce", "E-Commerce"),
                    ("marketing", "Digital Marketing"),
                    ("consulting", "Business Consulting"),
                    ("research", "Research & Analysis"),
                    ("api_integration", "API & Integrations"),
                    ("security", "Cybersecurity"),
                    ("blockchain", "Blockchain & Web3"),
                    ("iot", "IoT & Embedded"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="client_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="project",
            name="client_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="project",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("on_hold", "On Hold"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tech_stack",
            field=models.CharField(
                blank=True, help_text="Comma-separated tags", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
